title: FEZ Modding Wiki
description: Collection of resources for FEZ modding. 

readme_index:
  with_frontmatter: true

remote_theme: rundocs/jekyll-rtd-theme

toc: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
